{% set version = "0.2.2" %}
{% set build = "0" %}

package:
  name: pymt
  version: {{ version }}

source:
  url: https://github.com/csdms/pymt/archive/v{{ version }}.tar.gz
  sha256: 24d69a550944f1b1a51188e0d38d1348fdf7b9bfb65f7e546544ae8b2303ce60

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - xarray
    - shapely
    - netcdf4
    - pyyaml
    - esmpy
    - cfunits
    - jinja2
    - model_metadata
    - scripting
    - landlab

test:
  requires:
    - pytest
  imports:
    - pymt
  commands:
    - pytest --pyargs pymt --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  summary: Python package that provides services for coupling BMI components
  home: https://github.com/csdms/pymt
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/csdms/pymt
