{% set name = "pymt" %}
{% set version = "0.2.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/pymt
  git_tag: v{{ version }}

build:
  number: {{ build }}
  # string: beta_{{ build }}  # use number when out of beta
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - scipy >=0.17.0
    - matplotlib
    - xarray
    - shapely
    - netcdf4
    - pyyaml
    - esmpy
    - cfunits-python
    - jinja2
    - model_metadata
    - scripting
    - landlab

test:
  requires:
    - pytest
  imports:
    - pymt
  commands:
    - pytest --pyargs pymt --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  summary: Python package that provides services for coupling BMI components
  home: https://github.com/csdms/pymt
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/csdms/pymt
